package review

import (
	"fmt"
	"io"
	"os"
	"path"
	"regexp"
	"strings"

	"github.com/jklq/reviewd/internal/report"
)

// snapshotRoots opens the head and base snapshots for confinement-safe reads.
func snapshotRoots(head, base string) (map[string]*os.Root, error) {
	roots := map[string]*os.Root{}
	for name, dir := range map[string]string{"head": head, "base": base} {
		r, err := os.OpenRoot(dir)
		if err != nil {
			closeRoots(roots)
			return nil, err
		}
		roots[name] = r
	}
	return roots, nil
}

func closeRoots(roots map[string]*os.Root) {
	for _, r := range roots {
		r.Close()
	}
}

// SnapshotCoverage only flags unavailable content touched by this PR. Merely
// having submodules elsewhere in the repository does not lower merge confidence.
func SnapshotCoverage(head, base string, files []report.ChangedFile) ([]string, error) {
	roots, err := snapshotRoots(head, base)
	if err != nil {
		return nil, err
	}
	defer closeRoots(roots)
	var gaps []string
	for _, changed := range files {
		if !report.SafePath(changed.Filename) {
			return nil, fmt.Errorf("unsafe changed filename")
		}
		name, p := "head", changed.Filename
		if changed.Status == "removed" {
			name = "base"
		}
		f, err := roots[name].Open(p)
		if os.IsNotExist(err) {
			gaps = append(gaps, "Changed content is absent from the snapshot (possibly a submodule): "+p)
			continue
		}
		if err != nil {
			return nil, err
		}
		info, err := f.Stat()
		if err != nil {
			f.Close()
			return nil, err
		}
		if !info.Mode().IsRegular() {
			f.Close()
			gaps = append(gaps, "Changed path is not an ordinary file: "+p)
			continue
		}
		b, err := io.ReadAll(io.LimitReader(f, 256))
		f.Close()
		if err != nil {
			return nil, err
		}
		if strings.HasPrefix(string(b), "version https://git-lfs.github.com/spec/v1\n") {
			gaps = append(gaps, "Changed LFS content is a pointer, not hydrated source: "+p)
		}
	}
	return gaps, nil
}

// OmittedPatches reports changed files whose unified patch GitHub omitted and
// that reviewd cannot treat as a derived artifact. A generated file is a
// deterministic output of a reviewed source, so its omitted patch does not
// limit review; a hand-written file's omitted patch remains a coverage gap.
func OmittedPatches(head, base string, files []report.ChangedFile, omitted []string) ([]string, error) {
	if len(omitted) == 0 {
		return nil, nil
	}
	roots, err := snapshotRoots(head, base)
	if err != nil {
		return nil, err
	}
	defer closeRoots(roots)
	status := make(map[string]string, len(files))
	for _, f := range files {
		status[f.Filename] = f.Status
	}
	var gaps []string
	for _, name := range omitted {
		if !report.SafePath(name) {
			return nil, fmt.Errorf("unsafe changed filename")
		}
		root := roots["head"]
		if status[name] == "removed" {
			root = roots["base"]
		}
		if isDerived(root, name) {
			continue
		}
		gaps = append(gaps, "GitHub omitted the patch for "+name)
	}
	return gaps, nil
}

// derivedSuffixes names generated outputs that are mechanically reproduced from
// an input source, such as protobuf, Dart or bundle codegen.
var derivedSuffixes = []string{
	".pb.go", ".pb.cc", ".pb.cpp", ".pb.c", ".pb.h",
	"_pb2.py", "_pb2.pyi", "_pb2_grpc.py",
	".gen.go", "_gen.go", "_generated.go",
	".g.dart", ".freezed.dart",
	".min.js", ".min.css",
}

// derivedBanner matches the "generated code; do not edit" header that
// generators write to the top of derived files.
var derivedBanner = regexp.MustCompile(`(?i)(code generated .* do not edit|generated by .* do not edit|automatically generated|auto-generated)`)

// isDerived reports whether a changed file is a generated artifact whose
// omitted patch should not be counted as a coverage limitation.
func isDerived(root *os.Root, name string) bool {
	if derivedName(name) {
		return true
	}
	f, err := root.Open(name)
	if err != nil {
		return false
	}
	defer f.Close()
	b, err := io.ReadAll(io.LimitReader(f, 2048))
	if err != nil {
		return false
	}
	return derivedBanner.Match(b)
}

func derivedName(name string) bool {
	base := path.Base(name)
	if strings.HasPrefix(base, "zz_generated") || strings.HasPrefix(base, "generated.") {
		return true
	}
	for _, suffix := range derivedSuffixes {
		if strings.HasSuffix(name, suffix) {
			return true
		}
	}
	return false
}
